apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api-service
spec:
  type: NodePort
  selector:
    app: kubernetes-demo-api  # MATCHED
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31807